name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }} / ${{ matrix.database }}
    strategy:
      matrix:
        gemfile: [Gemfile]
        ruby: ["2.7.6"]
        database: [sqlite]
        include:
          - gemfile: Gemfile
            ruby: 2.7.6
            database: postgres
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DB: ${{ matrix.database }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Rails version
      if: ${{ matrix.gemfile == 'gemfiles/rails_edge.gemfile' }}
      run: bundle info rails | head -1
    - name: Set up database
      run: RAILS_ENV=test bundle exec rails db:setup
    - name: Ruby Tests
      run: bundle exec rails test
    - name: System Tests
      run: bundle exec rails test:system
    - name: RuboCop
      run: bundle exec rubocop
    - name: Archive system test artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: screenshots
        path: test/dummy/tmp/screenshots
